[workspace]
members = ["bin", "helpers", "day1"]
resolver = "2"

[profile.dev]
debug = true

[workspace.lints.clippy]
correctness = "warn"
suspicious = "warn"
complexity = "warn"
perf = "warn"
style = "warn"
pedantic = "warn"
missing_panics_doc = { level = "allow", priority = 1 }
