[package]
name = "bin"

[dependencies]
helpers = { version = "0.1.0", path = "../helpers" }
day1 = { version = "1.0.0", path = "../day1" }
day2 = { version = "1.0.0", path = "../day2" }
day3 = { version = "1.0.0", path = "../day3" }
day4 = { version = "1.0.0", path = "../day4" }
day5 = { version = "1.0.0", path = "../day5" }
day6 = { version = "1.0.0", path = "../day6" }
day7 = { version = "1.0.0", path = "../day7" }
day8 = { version = "1.0.0", path = "../day8" }
day9 = { version = "1.0.0", path = "../day9" }
day10 = { version = "1.0.0", path = "../day10" }
day11 = { version = "0.1.0", path = "../day11" }
day12 = { version = "0.1.0", path = "../day12" }
day13 = { version = "0.1.0", path = "../day13" }
day14 = { version = "0.1.0", path = "../day14" }
day15 = { version = "0.1.0", path = "../day15" }
day16 = { version = "0.1.0", path = "../day16" }
day17 = { version = "0.1.0", path = "../day17" }
day18 = { version = "0.1.0", path = "../day18" }
day19 = { version = "0.1.0", path = "../day19" }
day20 = { version = "0.1.0", path = "../day20" }
day21 = { version = "0.1.0", path = "../day21" }
day22 = { version = "0.1.0", path = "../day22" }
day23 = { version = "0.1.0", path = "../day23" }
day24 = { version = "0.1.0", path = "../day24" }

[lints]
workspace = true
